//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2025. All Rights Reserved.
//      RuleApp: Utilities
//      Date: 18 Jul 2025, 15:44:22
//      Generated by: Decision Server 9.5.0.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package calculator_embedded_client;

import calculator_embedded_client.invocation.CalculateOperationExecution;
import odm.Answer;
import odm.Calculator;

/**
 * Entry point of the application
 */
public class Main {

	/**
	 * Execution starts here...
	 */
	public static void main(String[] args) throws Exception {

		CalculateOperationExecution Calculate_Operation = new CalculateOperationExecution();

		// -- Create a new object for the input parameter
		Calculator calc_in = new Calculator();
		calc_in.arg1 = 10;
		calc_in.arg2 = 4;
		calc_in.operator = "*";

		Calculate_Operation.setCalculator(calc_in);

		// This method invokes the ruleset 'Calculate_Operation'.
		Calculate_Operation.run();

		// -- Get the output parameter object
		Answer answer_out = Calculate_Operation.getAnswer();
		System.out.println(">>>>> Result of calculation = " + answer_out.result + " <<<<<<<");

		Calculate_Operation.end();

	}

}
