//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2025. All Rights Reserved.
//      RuleApp: Utilities
//      Date: 18 Jul 2025, 15:44:22
//      Generated by: Decision Server 9.5.0.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package calculator_embedded_client.invocation;

import ilog.rules.res.session.IlrSessionRequest;
import ilog.rules.res.session.IlrSessionResponse;

/**
 * Wrapper class to facilitate the invocation of ruleset 'Calculate_Operation'
 */
public class CalculateOperationExecution extends RulesetExecution {

	private odm.Calculator calculator;

	/**
	 * Returns the calculator.
	 */
	public odm.Calculator getCalculator() {
		return calculator;
	}

	/**
	 * Sets the calculator.
	 */
	public void setCalculator(odm.Calculator calculator) {
		this.calculator = calculator;
	}

	private odm.Answer answer;

	/**
	 * Returns the answer.
	 */
	public odm.Answer getAnswer() {
		return answer;
	}

	/**
	 * Path to the latest ruleset 'Calculate_Operation' in the repository
	 */
	protected String getRulesetPath() {
		return "/Utilities/1.0/Calculate_Operation";
	}

	/**
	 * Initialize the request session with values for input parameters.
	 */
	protected void initRequest(IlrSessionRequest request) {
		request.setInputParameter("calculator", this.calculator);
	}

	/**
	 * Retrieves values in response to output parameters.
	 */
	protected void handleResponse(IlrSessionResponse response) {
		this.answer = (odm.Answer) response.getOutputParameters().get("answer");
	}

}
