//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2025. All Rights Reserved.
//      RuleApp: Utilities
//      Date: 18 Jul 2025, 15:44:22
//      Generated by: Decision Server 9.5.0.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package calculator_embedded_client.invocation;

/**
 * Raised when a ruleset invocation fails.
 */
public class RulesetExecutionException extends Exception {
	private static final long serialVersionUID = 1L;
	private String rulesetName;
	private Throwable cause;

	/**
	 * Raised when a ruleset invocation fails.
	 */
	public RulesetExecutionException(String rulesetName, Throwable cause) {
		this.rulesetName = rulesetName;
		this.cause = cause;
	}

	/**
	 * Returns the cause of the exception.
	 */
	public Throwable getCause() {
		return cause;
	}

	/**
	 * Returns the name of the ruleset.
	 */
	public String getRulesetName() {
		return rulesetName;
	}
}
