//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2025. All Rights Reserved.
//      RuleApp: Utilities
//      Date: 18 Jul 2025, 15:44:22
//      Generated by: Decision Server 9.5.0.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package calculator_embedded_client.invocation;

import ilog.rules.res.model.IlrPath;
import ilog.rules.res.session.IlrJ2SESessionFactory;
import ilog.rules.res.session.IlrSessionRequest;
import ilog.rules.res.session.IlrSessionResponse;
import ilog.rules.res.session.IlrStatelessSession;
import ilog.rules.res.session.config.IlrPersistenceType;
import ilog.rules.res.session.config.IlrSessionFactoryConfig;
import java.io.File;
import java.io.PrintWriter;

/**
 * Base class for ruleset invocation
 */
abstract class RulesetExecution {

	private static final String RULE_APP_DIRECTORY = "C:/temp/ODM Calculator/Deploy";

	private static IlrJ2SESessionFactory sessionFactory = null;

	/**
	 * Returns the ruleset path in the Rule Execution Server repository.
	 */
	protected abstract String getRulesetPath();

	/**
	 * Initialize the request session with values for input parameters.
	 */
	protected abstract void initRequest(IlrSessionRequest request);

	/**
	 * Retrieves values in response to output parameters.
	 */
	protected abstract void handleResponse(IlrSessionResponse response);

	/**
	 * Invokes the ruleset.
	 */
	public void run() throws RulesetExecutionException {
		IlrJ2SESessionFactory factory = getFactory();
		String rulesetPath = getRulesetPath();

		try {
			IlrSessionRequest request = factory.createRequest();

			request.setRulesetPath(IlrPath.parsePath(getRulesetPath()));
			initRequest(request);

			IlrSessionResponse response;
			IlrStatelessSession session = factory.createStatelessSession();

			response = session.execute(request);
			handleResponse(response);

		} catch (Exception e) {
			String rulesetName = rulesetPath.substring(rulesetPath.lastIndexOf("/"));
			throw new RulesetExecutionException(rulesetName, e);
		}
	}

	/**
	 * Ends the execution and free the eXecution Unit.
	 */
	public void end() {
		if (sessionFactory != null) {
			sessionFactory.release();
		}
	}

	private synchronized IlrJ2SESessionFactory getFactory() {
		if (sessionFactory == null) {
			IlrSessionFactoryConfig config = IlrJ2SESessionFactory.createDefaultConfig();
			config.getXUConfig().getPersistenceConfig().setPersistenceType(IlrPersistenceType.FILE);
			config.getXUConfig().getPersistenceConfig().getFilePersistenceConfig()
					.setDirectory(new File(RULE_APP_DIRECTORY));
			PrintWriter writer = new PrintWriter(System.out);
			config.getXUConfig().setLogWriter(writer);
			sessionFactory = new IlrJ2SESessionFactory(config);
		}
		return sessionFactory;
	}

}
